AS := mips-linux-gnu-as
ASFLAGS := -mips3 -march vr4300 -I include
OBJCOPY := mips-linux-gnu-objcopy
LD := mips-linux-gnu-ld
CC := ido-static-recomp-main/build/5.3/out/cc
CCFLAGS := -Xcpluscomm -O2 -mips2 -I include -non_shared -c -Wab,-r4300_mul -G 0
PYTHON := python3

OUTPUT := build

OBJECTS := \
    $(OUTPUT)/asm/header.o \
    $(OUTPUT)/assets/boot.o \
    $(OUTPUT)/asm/entry.o \
    $(OUTPUT)/asm/entry.o \
    $(OUTPUT)/asm/entry.o \
    $(OUTPUT)/asm/entry.o \
    $(OUTPUT)/asm/main.o \
    $(OUTPUT)/asm/sched.o \
    $(OUTPUT)/asm/control.o \
    $(OUTPUT)/asm/game1.o \
    $(OUTPUT)/asm/control2.o \
    $(OUTPUT)/asm/game2.o \
    $(OUTPUT)/asm/logo.o \
    $(OUTPUT)/asm/boss2.o \
    $(OUTPUT)/asm/sound1.o \
    $(OUTPUT)/asm/sound2.o \
    $(OUTPUT)/asm/rend1.o \
    $(OUTPUT)/asm/rend2.o \
    $(OUTPUT)/asm/getangle.o \
    $(OUTPUT)/asm/draw.o \
    $(OUTPUT)/asm/rnc.o \
    $(OUTPUT)/asm/display1.o \
    $(OUTPUT)/asm/cache1d.o \
    $(OUTPUT)/asm/display2.o \
    $(OUTPUT)/asm/actors1.o \
    $(OUTPUT)/asm/actors2.o \
    $(OUTPUT)/asm/actors3.o \
    $(OUTPUT)/asm/gamedef.o \
    $(OUTPUT)/src/engine.o \
    $(OUTPUT)/asm/game3.o \
    $(OUTPUT)/asm/game4.o \
    $(OUTPUT)/asm/player1.o \
    $(OUTPUT)/asm/player2.o \
    $(OUTPUT)/asm/player3.o \
    $(OUTPUT)/asm/premap.o \
    $(OUTPUT)/asm/sector.o \
    $(OUTPUT)/asm/board.o \
    $(OUTPUT)/asm/tile.o \
    $(OUTPUT)/asm/dukebot.o \
    $(OUTPUT)/asm/menues.o \
    $(OUTPUT)/asm/libultra/src/io/viblack.o \
    $(OUTPUT)/asm/libultra/src/os/initialize.o \
    $(OUTPUT)/asm/libultra/src/os/createthread.o \
    $(OUTPUT)/asm/libultra/src/os/startthread.o \
    $(OUTPUT)/asm/libultra/src/io/pimgr.o \
    $(OUTPUT)/asm/libultra/src/os/setthreadpri.o \
    $(OUTPUT)/asm/libultra/src/os/writebackdcacheall.o \
    $(OUTPUT)/asm/libultra/src/io/pigetstat.o \
    $(OUTPUT)/asm/libultra/src/io/epidma.o \
    $(OUTPUT)/asm/libultra/src/io/recvmesg.o \
    $(OUTPUT)/asm/libultra/src/os/gettime.o \
    $(OUTPUT)/asm/libultra/src/os/sendmesg.o \
    $(OUTPUT)/asm/libultra/src/os/createmesgqueue.o \
    $(OUTPUT)/asm/libultra/src/libc/ll.o \
    $(OUTPUT)/asm/libultra/src/io/visetyscale.o \
    $(OUTPUT)/asm/libultra/src/io/vimgr.o \
    $(OUTPUT)/asm/libultra/src/io/visetmode.o \
    $(OUTPUT)/asm/libultra/src/io/visetspecial.o \
    $(OUTPUT)/asm/libultra/src/os/seteventmesg.o \
    $(OUTPUT)/asm/libultra/src/io/visetevent.o \
    $(OUTPUT)/asm/libultra/src/os/setintmask.s.o \
    $(OUTPUT)/asm/libultra/src/io/sptaskyielded.o \
    $(OUTPUT)/asm/libultra/src/io/vigetcurrframebuf.o \
    $(OUTPUT)/asm/libultra/src/io/vigetnextframebuf.o \
    $(OUTPUT)/asm/libultra/src/io/viswapbuf.o \
    $(OUTPUT)/asm/libultra/src/io/sptask.o \
    $(OUTPUT)/asm/libultra/src/io/dpsetnextbuf.o \
    $(OUTPUT)/asm/libultra/src/io/sptaskyield.o \
    $(OUTPUT)/asm/libultra/src/io/contreaddata.o \
    $(OUTPUT)/asm/libultra/src/io/controller.o \
    $(OUTPUT)/asm/libultra/src/io/pfsinitpak.o \
    $(OUTPUT)/asm/libultra/src/io/pfsnumfiles.o \
    $(OUTPUT)/asm/libultra/src/io/pfsfreeblocks.o \
    $(OUTPUT)/asm/libultra/src/io/motor.o \
    $(OUTPUT)/asm/libultra/src/gu/translate.o \
    $(OUTPUT)/asm/libultra/src/gu/scale.o \
    $(OUTPUT)/asm/libultra/src/libc/sprintf.o \
    $(OUTPUT)/asm/libultra/src/libc/string.o \
    $(OUTPUT)/asm/libultra/src/io/pfsfilestate.o \
    $(OUTPUT)/asm/libultra/src/os/yieldthread.o \
    $(OUTPUT)/asm/libultra/src/io/pfsdeletefile.o \
    $(OUTPUT)/asm/libultra/src/io/pfsallocatefile.o \
    $(OUTPUT)/asm/libultra/src/io/pfsreadwritefile.o \
    $(OUTPUT)/asm/libultra/src/io/pfssearchfile.o \
    $(OUTPUT)/asm/libultra/src/io/pfsrepairid.o \
    $(OUTPUT)/asm/libultra/src/gu/rotate.o \
    $(OUTPUT)/asm/libultra/src/os/virtualtophysical.o \
    $(OUTPUT)/asm/libultra/src/audio/sl.o \
    $(OUTPUT)/asm/libultra/src/audio/heapalloc.o \
    $(OUTPUT)/asm/libultra/src/audio/heapinit.o \
    $(OUTPUT)/asm/libultra/src/audio/aisetfreq.o \
    $(OUTPUT)/asm/libultra/src/audio/sndplayer.o \
    $(OUTPUT)/asm/libultra/src/audio/bnkf.o \
    $(OUTPUT)/asm/libultra/src/audio/sndpallocate.o \
    $(OUTPUT)/asm/libultra/src/audio/csplayer.o \
    $(OUTPUT)/asm/libultra/src/audio/seqpsetbank.o \
    $(OUTPUT)/asm/libultra/src/audio/cspsetvol.o \
    $(OUTPUT)/asm/libultra/src/audio/sndpsetsound.o \
    $(OUTPUT)/asm/libultra/src/audio/sndpgetstate.o \
    $(OUTPUT)/asm/libultra/src/audio/sndpsetpitch.o \
    $(OUTPUT)/asm/libultra/src/audio/sndpsetpan.o \
    $(OUTPUT)/asm/libultra/src/audio/sndpsetvol.o \
    $(OUTPUT)/asm/libultra/src/audio/sndpplay.o \
    $(OUTPUT)/asm/libultra/src/audio/cspstop.o \
    $(OUTPUT)/asm/libultra/src/audio/cseq.o \
    $(OUTPUT)/asm/libultra/src/audio/cspsetseq.o \
    $(OUTPUT)/asm/libultra/src/audio/cspplay.o \
    $(OUTPUT)/asm/libultra/src/audio/sndpstop.o \
    $(OUTPUT)/asm/libultra/src/audio/synthesizer.o \
    $(OUTPUT)/asm/libultra/src/io/aisetnextbuf.o \
    $(OUTPUT)/asm/libultra/src/gu/sinf.o \
    $(OUTPUT)/asm/libultra/src/gu/cosf.o \
    $(OUTPUT)/asm/libultra/src/libc/llcvt.o \
    $(OUTPUT)/asm/libultra/src/gu/perspective.o \
    $(OUTPUT)/asm/libultra/src/gu/lookat.o \
    $(OUTPUT)/asm/libultra/src/gu/lookatref.o \
    $(OUTPUT)/asm/libultra/src/gu/mtxcatf.o \
    $(OUTPUT)/asm/libultra/src/gu/sqrtf.o \
    $(OUTPUT)/asm/libultra/src/os/interrupt.o \
    $(OUTPUT)/asm/libultra/src/io/vi.o \
    $(OUTPUT)/asm/libultra/src/os/setsr.o \
    $(OUTPUT)/asm/libultra/src/os/getsr.o \
    $(OUTPUT)/asm/libultra/src/os/setfpccsr.o \
    $(OUTPUT)/asm/libultra/src/io/sirawread.o \
    $(OUTPUT)/asm/libultra/src/io/sirawwrite.o \
    $(OUTPUT)/asm/libultra/src/os/exceptasm.o \
    $(OUTPUT)/asm/libultra/src/os/writebackdcache.o \
    $(OUTPUT)/asm/libultra/src/os/invalicache.o \
    $(OUTPUT)/asm/libultra/src/os/maptlbrdb.o \
    $(OUTPUT)/asm/libultra/src/io/pirawread.o \
    $(OUTPUT)/asm/libultra/src/libc/bzero.o \
    $(OUTPUT)/asm/libultra/src/os/thread.o \
    $(OUTPUT)/asm/libultra/src/io/cartrominit.o \
    $(OUTPUT)/asm/libultra/src/io/leodiskinit.o \
    $(OUTPUT)/asm/libultra/src/io/piacs.o \
    $(OUTPUT)/asm/libultra/src/os/getthreadpri.o \
    $(OUTPUT)/asm/libultra/src/io/pirawdma.o \
    $(OUTPUT)/asm/libultra/src/io/epirawdma.o \
    $(OUTPUT)/asm/libultra/src/io/devmgr.o \
    $(OUTPUT)/asm/libultra/src/7b230.o \
    $(OUTPUT)/asm/libultra/src/os/jammmesg.o \
    $(OUTPUT)/asm/libultra/src/io/pigetcmdq.o \
    $(OUTPUT)/asm/libultra/src/os/getcount.o \
    $(OUTPUT)/asm/libultra/src/os/timerintr.o \
    $(OUTPUT)/asm/libultra/src/io/vigetcurrcontext.o \
    $(OUTPUT)/asm/libultra/src/io/viswapcontext.o \
    $(OUTPUT)/asm/libultra/src/io/spgetstat.o \
    $(OUTPUT)/asm/libultra/src/libc/bcopy.o \
    $(OUTPUT)/asm/libultra/src/io/spsetstat.o \
    $(OUTPUT)/asm/libultra/src/io/spsetpc.o \
    $(OUTPUT)/asm/libultra/src/io/sprawdma.o \
    $(OUTPUT)/asm/libultra/src/io/sp.o \
    $(OUTPUT)/asm/libultra/src/io/dp.o \
    $(OUTPUT)/asm/libultra/src/io/siacs.o \
    $(OUTPUT)/asm/libultra/src/io/sirawdma.o \
    $(OUTPUT)/asm/libultra/src/os/settimer.o \
    $(OUTPUT)/asm/libultra/src/io/pfsgetstatus.o \
    $(OUTPUT)/asm/libultra/src/io/contpfs.o \
    $(OUTPUT)/asm/libultra/src/io/contramread.o \
    $(OUTPUT)/asm/libultra/src/io/pfschecker.o \
    $(OUTPUT)/asm/libultra/src/io/pfsisplug.o \
    $(OUTPUT)/asm/libultra/src/io/crc.o \
    $(OUTPUT)/asm/libultra/src/io/contramwrite.o \
    $(OUTPUT)/asm/libultra/src/gu/mtxutil.o \
    $(OUTPUT)/asm/libultra/src/libc/xprintf.o \
    $(OUTPUT)/asm/libultra/src/gu/normalize.o \
    $(OUTPUT)/asm/libultra/src/os/probetlb.o \
    $(OUTPUT)/asm/libultra/src/audio/syndelete.o \
    $(OUTPUT)/asm/libultra/src/audio/event.o \
    $(OUTPUT)/asm/libultra/src/audio/synaddplayer.o \
    $(OUTPUT)/asm/libultra/src/audio/synallocvoice.o \
    $(OUTPUT)/asm/libultra/src/audio/synstartvoice.o \
    $(OUTPUT)/asm/libultra/src/audio/synsetpan.o \
    $(OUTPUT)/asm/libultra/src/audio/synsetvol.o \
    $(OUTPUT)/asm/libultra/src/audio/synsetpitch.o \
    $(OUTPUT)/asm/libultra/src/audio/synsetfxmix.o \
    $(OUTPUT)/asm/libultra/src/audio/synstopvoice.o \
    $(OUTPUT)/asm/libultra/src/audio/synfreevoice.o \
    $(OUTPUT)/asm/libultra/src/audio/seqplayer.o \
    $(OUTPUT)/asm/libultra/src/audio/cents2ratio.o \
    $(OUTPUT)/asm/libultra/src/audio/synstartvoiceparam.o \
    $(OUTPUT)/asm/libultra/src/audio/drvrNew.o \
    $(OUTPUT)/asm/libultra/src/audio/synallocfx.o \
    $(OUTPUT)/asm/libultra/src/audio/mainbus.o \
    $(OUTPUT)/asm/libultra/src/audio/load.o \
    $(OUTPUT)/asm/libultra/src/audio/resample.o \
    $(OUTPUT)/asm/libultra/src/audio/env.o \
    $(OUTPUT)/asm/libultra/src/audio/auxbus.o \
    $(OUTPUT)/asm/libultra/src/audio/save.o \
    $(OUTPUT)/asm/libultra/src/io/ai.o \
    $(OUTPUT)/asm/libultra/src/io/si.o \
    $(OUTPUT)/asm/libultra/src/io/leointerrupt.o \
    $(OUTPUT)/asm/libultra/src/os/destroythread.o \
    $(OUTPUT)/asm/libultra/src/os/resetglobalintmask.o \
    $(OUTPUT)/asm/libultra/src/io/epirawwrite.o \
    $(OUTPUT)/asm/libultra/src/io/epirawread.o \
    $(OUTPUT)/asm/libultra/src/os/setglobalintmask.o \
    $(OUTPUT)/asm/libultra/src/os/setcompare.o \
    $(OUTPUT)/asm/libultra/src/os/invaldcache.o \
    $(OUTPUT)/asm/libultra/src/libc/xlitob.o \
    $(OUTPUT)/asm/libultra/src/libc/xldtob.o \
    $(OUTPUT)/asm/libultra/src/audio/copy.o \
    $(OUTPUT)/asm/libultra/src/audio/seq.o \
    $(OUTPUT)/asm/libultra/src/audio/synsetpriority.o \
    $(OUTPUT)/asm/libultra/src/audio/filter.o \
    $(OUTPUT)/asm/libultra/src/audio/reverb.o \
    $(OUTPUT)/asm/libultra/src/libc/ldiv.o \
    $(OUTPUT)/asm/data/ucode/boot.o \
    $(OUTPUT)/asm/data/ucode/rdp.o \
    $(OUTPUT)/asm/data/main.data.o \
    $(OUTPUT)/asm/data/sched.data.o \
    $(OUTPUT)/asm/data/control.data.o \
    $(OUTPUT)/asm/data/game1.data.o \
    $(OUTPUT)/asm/data/control2.data.o \
    $(OUTPUT)/asm/data/game2.data.o \
    $(OUTPUT)/asm/data/logo.data.o \
    $(OUTPUT)/asm/data/boss2.data.o \
    $(OUTPUT)/asm/data/sound1.data.o \
    $(OUTPUT)/asm/data/sound2.data.o \
    $(OUTPUT)/asm/data/rend1.data.o \
    $(OUTPUT)/asm/data/rend2.data.o \
    $(OUTPUT)/asm/data/getangle.data.o \
    $(OUTPUT)/asm/data/draw.data.o \
    $(OUTPUT)/asm/data/tileinfo.data.o \
    $(OUTPUT)/asm/data/display1.data.o \
    $(OUTPUT)/asm/data/cache1d.data.o \
    $(OUTPUT)/asm/data/display2.data.o \
    $(OUTPUT)/asm/data/actors1.data.o \
    $(OUTPUT)/asm/data/actors2.data.o \
    $(OUTPUT)/asm/data/actors3.data.o \
    $(OUTPUT)/asm/data/script.data.o \
    $(OUTPUT)/asm/data/engine.data.o \
    $(OUTPUT)/asm/data/game3.data.o \
    $(OUTPUT)/asm/data/player1.data.o \
    $(OUTPUT)/asm/data/player3.data.o \
    $(OUTPUT)/asm/data/sector.data.o \
    $(OUTPUT)/asm/data/tables.data.o \
    $(OUTPUT)/asm/data/dukebot.data.o \
    $(OUTPUT)/asm/data/menues.data.o \
    $(OUTPUT)/asm/data/global.data.o \
    $(OUTPUT)/asm/data/libultra/src/os/initialize.data.o \
    $(OUTPUT)/asm/data/libultra/src/io/pimgr.data.o \
    $(OUTPUT)/asm/data/libultra/src/io/vimgr.data.o \
    $(OUTPUT)/asm/data/libultra/src/io/vitbl.data.o \
    $(OUTPUT)/asm/data/libultra/src/io/controller.data.o \
    $(OUTPUT)/asm/data/libultra/src/audio/sl.data.o \
    $(OUTPUT)/asm/data/libultra/src/io/aisetnextbuf.data.o \
    $(OUTPUT)/asm/data/libultra/src/io/vi.data.o \
    $(OUTPUT)/asm/data/libultra/src/os/exceptasm.data.o \
    $(OUTPUT)/asm/data/libultra/src/os/thread.data.o \
    $(OUTPUT)/asm/data/libultra/src/io/piacs.data.o \
    $(OUTPUT)/asm/data/libultra/src/os/timerintr.data.o \
    $(OUTPUT)/asm/data/libultra/src/io/siacs.data.o \
    $(OUTPUT)/asm/data/libultra/src/libc/xprintf.data.o \
    $(OUTPUT)/asm/data/libultra/src/audio/drvrNew.data.o \
    $(OUTPUT)/asm/data/libultra/src/audio/env.data.o \
    $(OUTPUT)/asm/data/libultra/src/io/vimodepallan1.data.o \
    $(OUTPUT)/asm/data/libultra/src/io/vimodempallan1.data.o \
    $(OUTPUT)/asm/data/libultra/src/io/vimodentsclan1.data.o \
    $(OUTPUT)/asm/data/libultra/src/libc/xlitob.data.o \
    $(OUTPUT)/asm/data/ucode/boot.o \
    $(OUTPUT)/asm/data/ucode/rdp.o \
    $(OUTPUT)/asm/data/main.rodata.o \
    $(OUTPUT)/asm/data/sched.rodata.o \
    $(OUTPUT)/asm/data/control.rodata.o \
    $(OUTPUT)/asm/data/game1.rodata.o \
    $(OUTPUT)/asm/data/control2.rodata.o \
    $(OUTPUT)/asm/data/game2.rodata.o \
    $(OUTPUT)/asm/data/logo.rodata.o \
    $(OUTPUT)/asm/data/boss2.rodata.o \
    $(OUTPUT)/asm/data/sound1.rodata.o \
    $(OUTPUT)/asm/data/rend1.rodata.o \
    $(OUTPUT)/asm/data/rend2.rodata.o \
    $(OUTPUT)/asm/data/getangle.rodata.o \
    $(OUTPUT)/asm/data/draw.rodata.o \
    $(OUTPUT)/asm/data/cache1d.rodata.o \
    $(OUTPUT)/asm/data/display2.rodata.o \
    $(OUTPUT)/asm/data/actors1.rodata.o \
    $(OUTPUT)/asm/data/actors2.rodata.o \
    $(OUTPUT)/asm/data/actors3.rodata.o \
    $(OUTPUT)/asm/data/gamedef.rodata.o \
    $(OUTPUT)/asm/data/script.rodata.o \
    $(OUTPUT)/asm/data/game3.rodata.o \
    $(OUTPUT)/asm/data/game4.rodata.o \
    $(OUTPUT)/asm/data/player1.rodata.o \
    $(OUTPUT)/asm/data/player2.rodata.o \
    $(OUTPUT)/asm/data/player3.rodata.o \
    $(OUTPUT)/asm/data/premap.rodata.o \
    $(OUTPUT)/asm/data/sector.rodata.o \
    $(OUTPUT)/asm/data/board.rodata.o \
    $(OUTPUT)/asm/data/menues.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/os/setintmask.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/gu/rotate.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/audio/sndplayer.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/audio/csplayer.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/audio/synthesizer.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/gu/sinf.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/gu/cosf.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/gu/perspective.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/gu/lookatref.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/os/exceptasm.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/io/devmgr.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/libc/xprintf.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/audio/seqplayer.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/audio/cents2ratio.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/audio/drvrNew.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/audio/resample.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/audio/env.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/gu/libm_vals.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/libc/xldtob.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/audio/seq.rodata.o \
    $(OUTPUT)/asm/data/libultra/src/audio/reverb.rodata.o \
    $(OUTPUT)/asm/data/ucode/boot.o \
    $(OUTPUT)/asm/data/ucode/rdp.o \
    $(OUTPUT)/asm/data/ucode/rspucode.o \
    $(OUTPUT)/asm/data/main.bss.o \
    $(OUTPUT)/asm/data/control.bss.o \
    $(OUTPUT)/asm/data/game1.bss.o \
    $(OUTPUT)/asm/data/control2.bss.o \
    $(OUTPUT)/asm/data/game2.bss.o \
    $(OUTPUT)/asm/data/boss2.bss.o \
    $(OUTPUT)/asm/data/sound1.bss.o \
    $(OUTPUT)/asm/data/rend1.bss.o \
    $(OUTPUT)/asm/data/rend2.bss.o \
    $(OUTPUT)/asm/data/draw.bss.o \
    $(OUTPUT)/asm/data/rnc.bss.o \
    $(OUTPUT)/asm/data/cache1d.bss.o \
    $(OUTPUT)/asm/data/actors1.bss.o \
    $(OUTPUT)/asm/data/gamedef.bss.o \
    $(OUTPUT)/asm/data/engine.bss.o \
    $(OUTPUT)/asm/data/game4.bss.o \
    $(OUTPUT)/asm/data/player1.bss.o \
    $(OUTPUT)/asm/data/dukebot.bss.o \
    $(OUTPUT)/asm/data/menues.bss.o \
    $(OUTPUT)/asm/data/global.bss.o \
    $(OUTPUT)/asm/data/global2.bss.o \
    $(OUTPUT)/asm/data/libultra/src/os/initialize.bss.o \
    $(OUTPUT)/asm/data/libultra/src/io/pimgr.bss.o \
    $(OUTPUT)/asm/data/libultra/src/io/vimgr.bss.o \
    $(OUTPUT)/asm/data/libultra/src/os/seteventmesg.bss.o \
    $(OUTPUT)/asm/data/libultra/src/io/sptask.bss.o \
    $(OUTPUT)/asm/data/libultra/src/io/controller.bss.o \
    $(OUTPUT)/asm/data/libultra/src/io/motor.bss.o \
    $(OUTPUT)/asm/data/libultra/src/gu/rotate.bss.o \
    $(OUTPUT)/asm/data/libultra/src/io/cartrominit.bss.o \
    $(OUTPUT)/asm/data/libultra/src/io/leodiskinit.bss.o \
    $(OUTPUT)/asm/data/libultra/src/io/piacs.bss.o \
    $(OUTPUT)/asm/data/libultra/src/os/timerintr.bss.o \
    $(OUTPUT)/asm/data/libultra/src/io/siacs.bss.o \
    $(OUTPUT)/asm/data/libultra/src/io/pfsisplug.bss.o \
    $(OUTPUT)/asm/data/libultra/src/os/kdebugserver.bss.o \
    $(OUTPUT)/asm/data/libultra/src/io/leointerrupt.bss.o \
    $(OUTPUT)/asm/data/ucode/boot.o \
    $(OUTPUT)/asm/data/ucode/rdp.o \
    $(OUTPUT)/assets/rspucode.o \
    $(OUTPUT)/assets/palette.o \
    $(OUTPUT)/assets/tileblob.o \
    $(OUTPUT)/assets/board01.o \
    $(OUTPUT)/assets/board02.o \
    $(OUTPUT)/assets/board03.o \
    $(OUTPUT)/assets/board04.o \
    $(OUTPUT)/assets/board06.o \
    $(OUTPUT)/assets/board05.o \
    $(OUTPUT)/assets/board07.o \
    $(OUTPUT)/assets/board09.o \
    $(OUTPUT)/assets/board10.o \
    $(OUTPUT)/assets/board11.o \
    $(OUTPUT)/assets/board12.o \
    $(OUTPUT)/assets/board13.o \
    $(OUTPUT)/assets/board14.o \
    $(OUTPUT)/assets/board15.o \
    $(OUTPUT)/assets/board16.o \
    $(OUTPUT)/assets/board17.o \
    $(OUTPUT)/assets/board18.o \
    $(OUTPUT)/assets/board19.o \
    $(OUTPUT)/assets/board20.o \
    $(OUTPUT)/assets/board21.o \
    $(OUTPUT)/assets/board22.o \
    $(OUTPUT)/assets/board23.o \
    $(OUTPUT)/assets/board24.o \
    $(OUTPUT)/assets/board25.o \
    $(OUTPUT)/assets/board26.o \
    $(OUTPUT)/assets/board27.o \
    $(OUTPUT)/assets/board28.o \
    $(OUTPUT)/assets/board30.o \
    $(OUTPUT)/assets/board08.o \
    $(OUTPUT)/assets/board29.o \
    $(OUTPUT)/assets/board31.o \
    $(OUTPUT)/assets/board32.o \
    $(OUTPUT)/assets/board33.o \
    $(OUTPUT)/assets/board34.o \
    $(OUTPUT)/assets/soundctl.o \
    $(OUTPUT)/assets/soundtbl.o \
    $(OUTPUT)/assets/musicseq.o \
    $(OUTPUT)/assets/musicctl.o \
    $(OUTPUT)/assets/musictbl.o

dukenukem.bin : $(OUTPUT)/dukenukem.elf
	$(OBJCOPY) -O binary $< $@
	
$(OUTPUT)/%.o : %.c
	$(PYTHON) ./asm-processor/build.py $(CC) -- $(AS) $(ASFLAGS) -- $(CCFLAGS) -o $@ $<

$(OUTPUT)/%.o : %.s
	$(AS) $(ASFLAGS) $< -o $@

$(OUTPUT)/%.o : %.bin
	$(LD) -r -b binary -o $@ $<

$(OUTPUT)/dukenukem.elf : $(OBJECTS)
	$(LD) -T undefined_syms.txt -T dukenukem.ld -Map dukenukem.map -o $(OUTPUT)/dukenukem.elf

all: dukenukem.bin

objects: $(OBJECTS)
