int mulscale(long long a, long long b, long long c);
int mulscale1(long long a, long long b);
int mulscale2(long long a, long long b);
int mulscale3(long long a, long long b);
int mulscale4(long long a, long long b);
int mulscale5(long long a, long long b);
int mulscale6(long long a, long long b);
int mulscale7(long long a, long long b);
int mulscale8(long long a, long long b);
int mulscale9(long long a, long long b);
int mulscale10(long long a, long long b);
int mulscale11(long long a, long long b);
int mulscale12(long long a, long long b);
int mulscale13(long long a, long long b);
int mulscale14(long long a, long long b);
int mulscale15(long long a, long long b);
int mulscale16(long long a, long long b);
int mulscale17(long long a, long long b);
int mulscale18(long long a, long long b);
int mulscale19(long long a, long long b);
int mulscale20(long long a, long long b);
int mulscale21(long long a, long long b);
int mulscale22(long long a, long long b);
int mulscale23(long long a, long long b);
int mulscale24(long long a, long long b);
int mulscale25(long long a, long long b);
int mulscale26(long long a, long long b);
int mulscale27(long long a, long long b);
int mulscale28(long long a, long long b);
int mulscale29(long long a, long long b);
int mulscale30(long long a, long long b);
int mulscale31(long long a, long long b);
int mulscale32(long long a, long long b);
int dmulscale1(long long a, long long b, long long c, long long d);
int dmulscale2(long long a, long long b, long long c, long long d);
int dmulscale3(long long a, long long b, long long c, long long d);
int dmulscale4(long long a, long long b, long long c, long long d);
int dmulscale5(long long a, long long b, long long c, long long d);
int dmulscale6(long long a, long long b, long long c, long long d);
int dmulscale7(long long a, long long b, long long c, long long d);
int dmulscale8(long long a, long long b, long long c, long long d);
int dmulscale9(long long a, long long b, long long c, long long d);
int dmulscale10(long long a, long long b, long long c, long long d);
int dmulscale11(long long a, long long b, long long c, long long d);
int dmulscale12(long long a, long long b, long long c, long long d);
int dmulscale13(long long a, long long b, long long c, long long d);
int dmulscale14(long long a, long long b, long long c, long long d);
int dmulscale15(long long a, long long b, long long c, long long d);
int dmulscale16(long long a, long long b, long long c, long long d);
int dmulscale17(long long a, long long b, long long c, long long d);
int dmulscale18(long long a, long long b, long long c, long long d);
int dmulscale19(long long a, long long b, long long c, long long d);
int dmulscale20(long long a, long long b, long long c, long long d);
int dmulscale21(long long a, long long b, long long c, long long d);
int dmulscale22(long long a, long long b, long long c, long long d);
int dmulscale23(long long a, long long b, long long c, long long d);
int dmulscale24(long long a, long long b, long long c, long long d);
int dmulscale25(long long a, long long b, long long c, long long d);
int dmulscale26(long long a, long long b, long long c, long long d);
int dmulscale27(long long a, long long b, long long c, long long d);
int dmulscale28(long long a, long long b, long long c, long long d);
int dmulscale29(long long a, long long b, long long c, long long d);
int dmulscale30(long long a, long long b, long long c, long long d);
int dmulscale31(long long a, long long b, long long c, long long d);
int dmulscale32(long long a, long long b, long long c, long long d);
int divscale(long long a, long long b, char c);
int divscale1(long long a, long long b);
int divscale2(long long a, long long b);
int divscale3(long long a, long long b);
int divscale4(long long a, long long b);
int divscale5(long long a, long long b);
int divscale6(long long a, long long b);
int divscale7(long long a, long long b);
int divscale8(long long a, long long b);
int divscale9(long long a, long long b);
int divscale10(long long a, long long b);
int divscale11(long long a, long long b);
int divscale12(long long a, long long b);
int divscale13(long long a, long long b);
int divscale14(long long a, long long b);
int divscale15(long long a, long long b);
int divscale16(long long a, long long b);
int divscale17(long long a, long long b);
int divscale18(long long a, long long b);
int divscale19(long long a, long long b);
int divscale20(long long a, long long b);
int divscale21(long long a, long long b);
int divscale22(long long a, long long b);
int divscale23(long long a, long long b);
int divscale24(long long a, long long b);
int divscale25(long long a, long long b);
int divscale26(long long a, long long b);
int divscale27(long long a, long long b);
int divscale28(long long a, long long b);
int divscale29(long long a, long long b);
int divscale30(long long a, long long b);
int divscale31(long long a, long long b);
int divscale32(long long a, long long b);
int scale(int a, int b, int c);
int nsqrtasm(int a);
int klabs(int a);
int ksgn(int);

#define klabs2(x) (((x) > 0) ? (x) : -(x))
