.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel func_8004B400
    /* 1000 8004B400 3C088011 */  lui        $t0, %hi(main_BSS_START)
    /* 1004 8004B404 3C09001A */  lui        $t1, %hi(main_BSS_SIZE)
    /* 1008 8004B408 2508AC80 */  addiu      $t0, $t0, %lo(main_BSS_START)
    /* 100C 8004B40C 35293B30 */  ori        $t1, $t1, %lo(main_BSS_SIZE)
  .L8004B410:
    /* 1010 8004B410 2129FFF8 */  addi       $t1, $t1, -0x8 /* handwritten instruction */
    /* 1014 8004B414 AD000000 */  sw         $zero, 0x0($t0)
    /* 1018 8004B418 AD000004 */  sw         $zero, 0x4($t0)
    /* 101C 8004B41C 1520FFFC */  bnez       $t1, .L8004B410
    /* 1020 8004B420 21080008 */   addi      $t0, $t0, 0x8 /* handwritten instruction */
    /* 1024 8004B424 3C0A8005 */  lui        $t2, %hi(boot)
    /* 1028 8004B428 3C1D8011 */  lui        $sp, %hi(D_8010AC88+0x4000)
    /* 102C 8004B42C 254AB450 */  addiu      $t2, $t2, %lo(boot)
    /* 1030 8004B430 01400008 */  jr         $t2
    /* 1034 8004B434 27BDEC88 */   addiu     $sp, $sp, %lo(D_8010AC88+0x4000)
    /* 1038 8004B438 00000000 */  nop
    /* 103C 8004B43C 00000000 */  nop
    /* 1040 8004B440 00000000 */  nop
    /* 1044 8004B444 00000000 */  nop
    /* 1048 8004B448 00000000 */  nop
    /* 104C 8004B44C 00000000 */  nop
