.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel func_800BB2F0
    /* 70EF0 800BB2F0 3C088000 */  lui        $t0, 0x8000
    /* 70EF4 800BB2F4 240A2000 */  addiu      $t2, $zero, 0x2000
    /* 70EF8 800BB2F8 010A4821 */  addu       $t1, $t0, $t2
    /* 70EFC 800BB2FC 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L800BB300:
    /* 70F00 800BB300 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 70F04 800BB304 0109082B */  sltu       $at, $t0, $t1
    /* 70F08 800BB308 1420FFFD */  bnez       $at, .L800BB300
    /* 70F0C 800BB30C 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 70F10 800BB310 03E00008 */  jr         $ra
    /* 70F14 800BB314 00000000 */   nop
    /* 70F18 800BB318 00000000 */  nop
    /* 70F1C 800BB31C 00000000 */  nop
